room_type = [
            "DEBUG_ROOM_TYPE",
            "LczArmory",
            "LczCurve",
            "LczStraight",
            "Lcz330",
            "Lcz914",
            "LczCrossing",
            "LczTCross",
            "LczCafe",
            "LczPlants",
            "LczToilets",
            "LczAirlock",
            "Lcz173",
            "LczClassDSpawn",
            "LczCheckpointB",
            "LczGlassBox",
            "LczCheckpointA",
            "Hcz079",
            "HczEzCheckpointA",
            "HczEzCheckpointB",
            "HczArmory",
            "Hcz939",
            "HczHid",
            "Hcz049",
            "HczChkpA",
            "HczCrossing",
            "Hcz106",
            "HczNuke",
            "HczTesla",
            "HczServers",
            "HczChkpB",
            "HczTCross",
            "HczCurve",
            "Hcz096",
            "EzVent",
            "EzIntercom",
            "EzGateA",
            "EzDownstairsPcs",
            "EzCurve",
            "EzPcs",
            "EzCrossing",
            "EzCollapsedTunnel",
            "EzConference",
            "EzStraight",
            "EzCafeteria",
            "EzUpstairsPcs",
            "EzGateB",
            "EzShelter",
            "Pocket",
            "Surface",
            "EzCheckpointHallway",
            "HczTestRoom"
        ]

item_type = [
            "DEBUG_ITEM_TYPE",
            "KeycardJanitor", "0",
            "KeycardScientist", "1",
            "KeycardResearchCoordinator", "2",
            "KeycardZoneManager", "3",
            "KeycardGuard", "4",
            "KeycardNTFOfficer", "5",
            "KeycardContainmentEngineer", "6",
            "KeycardNTFLieutenant", "7",
            "KeycardNTFCommander", "8",
            "KeycardFacilityManager", "9",
            "KeycardChaosInsurgency", "10",
            "KeycardO5", "11",
            "Radio", "12",
            "GunCOM15", "13",
            "Medkit", "14",
            "Flashlight", "15",
            "MicroHID", "16",
            "SCP500", "17",
            "SCP207", "18",
            "Ammo12gauge", "19",
            "GunE11SR", "20",
            "GunCrossvec", "21",
            "Ammo556x45", "22",
            "GunFSP9", "23",
            "GunLogicer", "24",
            "GrenadeHE", "25",
            "GrenadeFlash", "26",
            "Ammo44cal", "27",
            "Ammo762x39", "28",
            "Ammo9x19", "29",
            "GunCOM18", "30",
            "SCP018", "31",
            "SCP268", "32",
            "Adrenaline", "33",
            "Painkillers", "34",
            "Coin", "35",
            "ArmorLight", "36",
            "ArmorCombat", "37",
            "ArmorHeavy", "38",
            "GunRevolver", "39",
            "GunAK", "40",
            "GunShotgun", "41",
            "SCP330", "42",
            "SCP2176", "43",
            "SCP244a", "44",
            "SCP244b", "45",
            "SCP1853", "46",
            "ParticleDisruptor", "47",
            "GunCom45", "48",
            "SCP1576", "49",
            "Jailbird", "50",
        ]

effect_type = [
            "DEBUG_EFFECT_TYPE",
            "AmnesiaItems",
            "AmnesiaVision",
            "Asphyxiated",
            "Bleeding",
            "Blinded",
            "Burned",
            "Concussed",
            "Corroding",
            "Deafened",
            "Decontaminating",
            "Disabled",
            "Ensnared",
            "Exhausted",
            "Flashed",
            "Hemorrhage",
            "Invigorated",
            "BodyshotReduction",
            "Poisoned",
            "Scp207",
            "Invisible",
            "SinkHole",
            "DamageReduction",
            "MovementBoost",
            "RainbowTaste",
            "SeveredHands",
            "Stained",
            "Vitality",
            "Hypothermia",
            "Scp1853",
            "CardiacArrest",
            "InsufficientLighting",
            "SoundtrackMute",
            "AntiScp207",
            "Scanned"
        ]

role_type = [
            "DEBUG_ROLE_TYPE",
            "Spectator",
            "CustomRole",
            "Overwatch",
            "Filmmaker",
            "Tutorial",
            "Scp173",
            "Scp106",
            "Scp049",
            "Scp0492",
            "Scp079",
            "Scp096",
            "Scp939",
            "ClassD",
            "Scientist",
            "FacilityGuard",
            "NtfPrivate",
            "NtfSergeant",
            "NtfSpecialist",
            "NtfCaptain",
            "ChaosConscript",
            "ChaosRifleman",
            "ChaosRepressor",
            "ChaosMarauder"
        ]

door_type = [
            "DEGUG_DOOR_TYPE",
            "Scp914Door",
            "GR18Inner",
            "Scp049Gate",
            "Scp049Armory",
            "Scp079First",
            "Scp079Second",
            "Scp096",
            "Scp106Primary",
            "Scp106Secondary",
            "Scp173Gate",
            "Scp173Connector",
            "Scp173Armory",
            "Scp173Bottom",
            "GR18Gate",
            "Scp914Gate",
            "Scp939Cryo",
            "CheckpointLczA",
            "CheckpointLczB",
            "EntranceDoor",
            "EscapePrimary",
            "EscapeSecondary",
            "ServersBottom",
            "GateA",
            "GateB",
            "HczArmory",
            "HeavyContainmentDoor",
            "HID",
            "HIDLeft",
            "HIDRight",
            "Intercom",
            "LczArmory",
            "LczCafe",
            "LczWc",
            "LightContainmentDoor",
            "NukeArmory",
            "NukeSurface",
            "PrisonDoor",
            "SurfaceGate",
            "Scp330",
            "Scp330Chamber",
            "CheckpointGate",
            "SurfaceDoor",
            "CheckpointEzHczA",
            "CheckpointEzHczB",
            "UnknownGate",
            "UnknownElevator",
            "ElevatorGateA",
            "ElevatorGateB",
            "ElevatorNuke",
            "ElevatorScp049",
            "ElevatorLczA",
            "ElevatorLczB",
            "CheckpointArmoryA",
            "CheckpointArmoryB",
            "Airlock",
        ]

se_variable = [
    "DEBUG_SE_VARIABLE",
    "{CASSIESPEAKING}", "{!CASSIESPEAKING}",
    "{DECONTAMINATED}", "{!DECONTAMINATED}",
    "{ISRUNNING}", "{!ISRUNNING}",
    "{ROUNDENDED}", "{!ROUNDENDED}",
    "{ROUNDINPROGRESS}", "{!ROUNDINPROGRESS}",
    "{ROUNDSTARTED}", "{!ROUNDSTARTED}",
    "{SCP914ACTIVE}", "{!SCP914ACTIVE}",
    "{WARHEADCOUNTING}", "{!WARHEADCOUNTING}",
    "{!WARHEADDETONATED}", "{!WARHEADDETONATED}",
    "{WAVERESPAWNING}", "{!WAVERESPAWNING}",
    "{INTERCOMINUSE}", "{INTERCOMREADY}",
    "{HEAVILYMODDED}", "{!HEAVILYMODDED}",
    "{CHANCE}",
    "{CHANCE10}",
    "{CHANCE100}",
    "{CHANCE20}",
    "{CHANCE3}",
    "{CHANCE5}",
    "{CLASSDESCAPES}",
    "{ESCAPES}",
    "{SCIENTISTESCAPES}",
    "{INTERCOMCOOLDOWN}",
    "{INTERCOMUSETIME}",
    "{DETONATIONTIME}",
    "{ENGAGEDGENERATORS}",
    "{PLAYERS}",
    "{PLAYERSALIVE}",
    "{PLAYERSDEAD}",
    "{ROUNDMINUTES}",
    "{ROUNDSECONDS}",
    "{MAXPLAYERS}",
    "{IP}", "{PORT}",
    "{DOORSTATE}",
    "{LASTRESPAWNTEAM}",
    "{LASTRESPAWNUNIT}",
    "{NEXTWAVE}",
    "{SHOW}",
    "{CHAOSTICKETS}",
    "{NTFTICKETS}",
    "{RESPAWNEDPLAYERS}",
    "{TIMESINCELASTWAVE}",
    "{TIMEUNTILNEXTWAVE}",
    "{TOTALWAVES}"
    "{DAYOFMONTH}"
    "{DAYOFWEEK}"
    "{DAYOFYEAR}"
    "{MONTH}"
    "{TICK}"
    "{YEAR}"
    "{KILLS}"
    "{SCPKILLS}",
]

se_player_variable = [
    "DEBUG_SE_PLAYER_VARIABLE",
    "{CI}",
    "{GUARDS}", "{MTFANDGUARDS}", "{MTF}",
    "{SCPS}",
    "{SH}", "{UIU}",
    "{INTERCOMSPEAKER}",
    "{SERVERSTAFF}",
    "{RESPAWNEDPLAYERS}",
    "{EZ}",
    "{HCZ}",
    "{LCZ}",
    "{POCKET}",
    "{SURFACE}",
    "{RESPAWNEDPLAYERS}",
    "{EVPLAYER}"
]

enable_disable_key = [
    "DROPPING",
    "DYING",
    "ESCAPING",
    "ELEVATORS",
    "GENERATORS",
    "HAZARDS",
    "HURTING",
    "ITEMPICKUPS",
    "LOCKERS",
    "MICROPIKUPS",
    "NTFANNOUNCEMENT",
    "PEDESTALS",
    "RESPAWNS",
    "SCP330",
    "SCP914",
    "SHOOTING",
    "TESLAS",
    "WARHEAD",
    "WORKSTATIONS"
]